apiVersion: v1
kind: Service
metadata:
  name: joomla
  labels:
    app: web
spec:
  ports:
  - port: 80
  selector:
    env: prod
    dc: IN
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    frontend: web
    backend: db
spec:
  selector:
    matchLabels: 
      env: prod
      dc: IN
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: web-pod
      labels:
        env: prod
        dc: IN
    spec:
      containers:
      - name: web-con
        image: joomla:3.9.18-php7.4-apache
        env:
        - name: JOOMLA_DB_HOST
          value: mysql
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_pass
        ports:
        - containerPort: 80
          name: web-con
        volumeMounts: 
        - name: web-pv-claim
          mountPath: /var/www/html
      volumes:
      - name: web-pv-claim
        persistentVolumeClaim: 
          claimName: efs-joomla