apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: sql
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    env: prod
    dc: IN

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: sql
    type: backend
spec:
  selector:
    matchLabels:
      env: prod
      dc: IN
  template:
    metadata:
      name:
        sql-pod
      labels:
        env: prod
        dc: IN
    spec:
      containers:
      - name: mysql-con
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: rootpass
        ports:
        - containerPort: 3306
          name: mysql-con
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/sql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: efs-mysql