kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs
provisioner: eks/efs
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi